### ISSUE TITLE
I borrowed your code

### ISSUE THREAD

**Issue by JeremyMarshall** [unsignedmind/react-apollo-client-typescript#2]
Thanks for doing this

I was getting all the typescript/react/apollo stuff in a mess. I had a GQL server and need a frontend to it.

This is perfect. I'll swap in my schema and hopefully do minimal changes

this is where I [forked](https://github.com/bythepowerof/react-ts-apollo-client-app.git) it to 

The server is in go [gqlgen](https://gqlgen.com) and the actual process is Kubernetes [kubebuilder](https://book.kubebuilder.io)

**Comment by unsignedmind** [comment]
I'm glad it helps. Have Fun :). I'll have a look at your repo. Sounds interesting.
